definitions:
  dto.AuthLoginRequest:
    properties:
      email:
        type: string
      password:
        minLength: 6
        type: string
    required:
    - email
    - password
    type: object
  dto.AuthLoginResponse:
    properties:
      error:
        type: string
      message:
        type: string
      result:
        $ref: '#/definitions/dto.LoginAllData'
      success:
        type: boolean
    type: object
  dto.AuthRegisterRequest:
    properties:
      confirmPassword:
        type: string
      email:
        type: string
      password:
        type: string
    required:
    - confirmPassword
    - email
    - password
    type: object
  dto.AuthRegisterResponse:
    properties:
      error:
        type: string
      message:
        type: string
      success:
        type: boolean
    type: object
  dto.LinksResponse:
    properties:
      error:
        type: string
      has_next:
        type: boolean
      limit:
        type: integer
      message:
        type: string
      page:
        type: integer
      result: {}
      success:
        type: boolean
    type: object
  dto.LoginAllData:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/dto.UserData'
    type: object
  dto.ShortLinksRequest:
    properties:
      original_url:
        type: string
      slug:
        type: string
    required:
    - original_url
    type: object
  dto.UserData:
    properties:
      email:
        type: string
      id:
        type: integer
    type: object
  dto.UserResponse:
    properties:
      error:
        type: string
      message:
        type: string
      result: {}
      success:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/links:
    get:
      description: Get paginated short links for authenticated user (forward pagination
        using has_next)
      parameters:
      - default: 1
        description: Page number
        in: query
        name: page
        type: integer
      - default: 4
        description: Limit per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success response with pagination (page, limit, has_next)
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.LinksResponse'
      security:
      - BearerAuth: []
      summary: Get all short links
      tags:
      - Links
    post:
      consumes:
      - application/json
      description: Create a new short link for authenticated user
      parameters:
      - description: Short Link Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.ShortLinksRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Link created successfully
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "409":
          description: Slug already taken
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.LinksResponse'
      security:
      - BearerAuth: []
      summary: Create short link
      tags:
      - Links
  /api/links/{id}:
    delete:
      description: Delete a link by its ID (only owner can delete)
      parameters:
      - description: Link ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Link deleted successfully
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "400":
          description: Invalid ID
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "404":
          description: Link not found or unauthorized
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.LinksResponse'
      security:
      - BearerAuth: []
      summary: Delete link by id
      tags:
      - Links
  /api/links/{slug}:
    get:
      description: Get a specific short link by slug for authenticated user
      parameters:
      - description: Short link slug
        in: path
        name: slug
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "400":
          description: Slug is required
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "404":
          description: Link not found
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.LinksResponse'
      security:
      - BearerAuth: []
      summary: Get link by slug
      tags:
      - Links
  /api/login:
    post:
      consumes:
      - application/json
      description: Authenticate user with email and password
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AuthLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.AuthLoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.AuthLoginResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.AuthLoginResponse'
      summary: Login user
      tags:
      - Authentication
  /api/register:
    post:
      consumes:
      - application/json
      description: Register a new user account
      parameters:
      - description: Register Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.AuthRegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Register success
          schema:
            $ref: '#/definitions/dto.AuthRegisterResponse'
        "400":
          description: Invalid input / validation error
          schema:
            $ref: '#/definitions/dto.AuthRegisterResponse'
        "409":
          description: Email already exists
          schema:
            $ref: '#/definitions/dto.AuthRegisterResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.AuthRegisterResponse'
      summary: Register user
      tags:
      - Authentication
  /api/users/email/{email}:
    get:
      consumes:
      - application/json
      description: Get user data based on email
      parameters:
      - description: User Email
        in: path
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.UserResponse'
      security:
      - BearerAuth: []
      summary: Get user by email
      tags:
      - Users
  /api/users/image:
    patch:
      consumes:
      - multipart/form-data
      description: Update profile image for authenticated user
      parameters:
      - description: User image file
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.UserResponse'
      security:
      - BearerAuth: []
      summary: Update user image
      tags:
      - Users
  /api/users/me:
    get:
      consumes:
      - application/json
      description: Get logged-in user data from JWT
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.UserResponse'
      security:
      - BearerAuth: []
      summary: Get current user
      tags:
      - Users
  /r/{slug}:
    get:
      description: Redirect user to original URL using slug and increment click count
      parameters:
      - description: Short link slug
        in: path
        name: slug
        required: true
        type: string
      responses:
        "302":
          description: Redirect to original URL
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "404":
          description: Link not found
          schema:
            $ref: '#/definitions/dto.LinksResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/dto.LinksResponse'
      summary: Redirect to original URL
      tags:
      - Links
securityDefinitions:
  BearerAuth:
    description: 'Masukkan token dengan format: Bearer <token>'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
